### ISSUE TITLE
Can't log in with the token

### ISSUE THREAD

**Issue by josephschwart2245** [TRoboto/datacamp-downloader#29]
## Error Message

System: macOS 11.2.3

```
➜  ~ datacamp set-token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
Please wait /Traceback (most recent call last):
  File "/Users/xxx/anaconda3/bin/datacamp", line 8, in <module>
    sys.exit(app())
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/datacamp_downloader/downloader.py", line 48, in set_token
    datacamp.set_token(token)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/datacamp_downloader/helper.py", line 63, in wrapper
    output = f(*args)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/datacamp_downloader/datacamp_utils.py", line 129, in set_token
    self.session.restart()
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/datacamp_downloader/session.py", line 48, in restart
    self.savefile.unlink(missing_ok=True)
TypeError: unlink() got an unexpected keyword argument 'missing_ok'
Please wait |
```

**Comment by TRoboto** [comment]
What python version do you use?

**Comment by josephschwart2245** [comment]
Sorry, I forgot to provide this information.

```
python --version
Python 3.7.3

which python
/Users/xxxx/anaconda3/bin/python
```

**Comment by TRoboto** [comment]
This makes sense and will be resolved soon. For now, I recommend you to use Python 3.8 or higher.

**Comment by josephschwart2245** [comment]
Got it, Thank you!

**Comment by TRoboto** [comment]
Thank you for reporting this issue, much appreciated!

**Comment by TRoboto** [comment]
This issue has been fixed. Would you mind confirming it? @josephschwart2245 

To install the fixed version, please follow the installation from source steps [here](https://github.com/TRoboto/datacamp-downloader#from-source)

**Comment by TRoboto** [comment]
It's now confirmed that the solution works, so this issue is closed.
