### ISSUE TITLE
datacamp tracks - not working

### ISSUE THREAD

**Issue by pr2tik1** [TRoboto/datacamp-downloader#36]
ERROR : `datacamp tracks` command is not working

ERROR MESSAGE : 

Please wait \Traceback (most recent call last):
  File "/home/pratik/anaconda3/bin/datacamp", line 8, in <module>
    sys.exit(app())
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/datacamp_downloader/downloader.py", line 58, in tracks
    datacamp.list_completed_tracks(refresh)
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/datacamp_downloader/datacamp_utils.py", line 43, in wrapper
    return f(*args, **kwargs)
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/datacamp_downloader/helper.py", line 64, in wrapper
    output = f(*args)
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/datacamp_downloader/datacamp_utils.py", line 144, in list_completed_tracks
    self.get_completed_tracks()
  File "/home/pratik/anaconda3/lib/python3.8/site-packages/datacamp_downloader/datacamp_utils.py", line 356, in get_completed_tracks
    courses.update(track.courses)
AttributeError: 'list' object has no attribute 'update'

**Comment by TRoboto** [comment]
Thanks for reporting this bug. Please install the tool again using `pip install git+https://github.com/TRoboto/datacamp-downloader` and test again.

**Comment by pr2tik1** [comment]
Shows s
ame error.

**Comment by TRoboto** [comment]
If it shows exactly the same error, this means you still use the old version. I would suggest that you create a new virtual env, and install the tool their using the above command and test again. If an error occurs, it should be different. One more thing, does `datacamp courses` command work?

**Comment by pr2tik1** [comment]
Okay I will check, soon, currently using `datacamp download all`. And the command `datacamp courses` is working perfectly fine. Also would like to suggest if the quality of videos can be given as an option. Thanks for a great tool!

**Comment by TRoboto** [comment]
Glad to see the tool help you. I'll be waiting for you!

**Comment by pr2tik1** [comment]
> If it shows exactly the same error, this means you still use the old version. I would suggest that you create a new virtual env, and install the tool their using the above command and test again. If an error occurs, it should be different. One more thing, does `datacamp courses` command work?

Hi, it works fine. The problem was in environment. This helped me.
