### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by haohoangofficial** [TRoboto/datacamp-downloader#48]
I try command `datacamp set-token [TOKEN]` but I have a errors below
I using Python version 3.9.6
How to fix it?
Thanks!
`Please wait —Process Process-1:
Traceback (most recent call last):
  File "c:\users\hao\appdata\local\programs\python\python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\hao\appdata\local\programs\python\python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\hao\appdata\local\programs\python\python39\lib\site-packages\undetected_chromedriver\dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "c:\users\hao\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\hao\appdata\local\programs\python\python39\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "c:\users\hao\appdata\local\programs\python\python39\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "c:\users\hao\appdata\local\programs\python\python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of "filename".
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by TRoboto** [comment]
I am not sure where the problem is. Try to install and use the tool in a new virtual environment.

**Comment by HannaAA17** [comment]
same for me

**Comment by TRoboto** [comment]
You will need to install chrome driver as in issue #51.

**Comment by TRoboto** [comment]
Closing due to inactivity.
