### ISSUE TITLE
Cannot determine loading status

### ISSUE THREAD

**Issue by NathanZorndorf** [TRoboto/datacamp-downloader#58]
When I run `datacamp courses` I get the following error (after logging in successfully). 

+--------+------------------------------------------+------------+------------+------------+        
| ID     | Title                                    | Datasets   | Exercises  | Videos     |
+--------+------------------------------------------+------------+------------+------------+
Please wait —Traceback (most recent call last):
  File "/Users/naekid/opt/anaconda3/envs/personal/bin/datacamp", line 8, in <module>
    sys.exit(app())
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/datacamp_downloader/downloader.py", line 67, in courses
    datacamp.list_completed_courses(refresh)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/datacamp_downloader/datacamp_utils.py", line 44, in wrapper
    return f(*args, **kwargs)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/datacamp_downloader/helper.py", line 72, in wrapper
    output = f(*args)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/datacamp_downloader/datacamp_utils.py", line 181, in list_completed_courses
    for i, course in enumerate(self.get_completed_courses(refresh), 1):
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/datacamp_downloader/datacamp_utils.py", line 409, in get_completed_courses
    data = self.get_profile_data()
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/datacamp_downloader/datacamp_utils.py", line 154, in get_profile_data
    PROFILE_DATA_URL.format(slug=self.login_data["slug"])
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/datacamp_downloader/session.py", line 84, in get_json
    page = self.get(url)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/datacamp_downloader/session.py", line 79, in get
    self.driver.get(url)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 535, in get
    return super().get(url)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/Users/naekid/opt/anaconda3/envs/personal/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.114)
Stacktrace:
0   4ec4aa7ac73be214_chromedriver       0x0000000106e14079 4ec4aa7ac73be214_chromedriver + 4444281
1   4ec4aa7ac73be214_chromedriver       0x0000000106da0403 4ec4aa7ac73be214_chromedriver + 3970051
2   4ec4aa7ac73be214_chromedriver       0x0000000106a3b038 4ec4aa7ac73be214_chromedriver + 409656
3   4ec4aa7ac73be214_chromedriver       0x0000000106a283c8 4ec4aa7ac73be214_chromedriver + 332744
4   4ec4aa7ac73be214_chromedriver       0x0000000106a27ac7 4ec4aa7ac73be214_chromedriver + 330439
5   4ec4aa7ac73be214_chromedriver       0x0000000106a27047 4ec4aa7ac73be214_chromedriver + 327751
6   4ec4aa7ac73be214_chromedriver       0x0000000106a25f16 4ec4aa7ac73be214_chromedriver + 323350
7   4ec4aa7ac73be214_chromedriver       0x0000000106a2644c 4ec4aa7ac73be214_chromedriver + 324684
8   4ec4aa7ac73be214_chromedriver       0x0000000106a333bf 4ec4aa7ac73be214_chromedriver + 377791
9   4ec4aa7ac73be214_chromedriver       0x0000000106a33f22 4ec4aa7ac73be214_chromedriver + 380706
10  4ec4aa7ac73be214_chromedriver       0x0000000106a425b3 4ec4aa7ac73be214_chromedriver + 439731
11  4ec4aa7ac73be214_chromedriver       0x0000000106a4647a 4ec4aa7ac73be214_chromedriver + 455802
12  4ec4aa7ac73be214_chromedriver       0x0000000106a2677e 4ec4aa7ac73be214_chromedriver + 325502
13  4ec4aa7ac73be214_chromedriver       0x0000000106a421fa 4ec4aa7ac73be214_chromedriver + 438778
14  4ec4aa7ac73be214_chromedriver       0x0000000106aa162d 4ec4aa7ac73be214_chromedriver + 828973
15  4ec4aa7ac73be214_chromedriver       0x0000000106a8e683 4ec4aa7ac73be214_chromedriver + 751235
16  4ec4aa7ac73be214_chromedriver       0x0000000106a64a45 4ec4aa7ac73be214_chromedriver + 580165
17  4ec4aa7ac73be214_chromedriver       0x0000000106a65a95 4ec4aa7ac73be214_chromedriver + 584341
18  4ec4aa7ac73be214_chromedriver       0x0000000106de555d 4ec4aa7ac73be214_chromedriver + 4253021
19  4ec4aa7ac73be214_chromedriver       0x0000000106dea3a1 4ec4aa7ac73be214_chromedriver + 4273057
20  4ec4aa7ac73be214_chromedriver       0x0000000106def16f 4ec4aa7ac73be214_chromedriver + 4292975
21  4ec4aa7ac73be214_chromedriver       0x0000000106deadea 4ec4aa7ac73be214_chromedriver + 4275690
22  4ec4aa7ac73be214_chromedriver       0x0000000106dc454f 4ec4aa7ac73be214_chromedriver + 4117839
23  4ec4aa7ac73be214_chromedriver       0x0000000106e04ed8 4ec4aa7ac73be214_chromedriver + 4382424
24  4ec4aa7ac73be214_chromedriver       0x0000000106e0505f 4ec4aa7ac73be214_chromedriver + 4382815
25  4ec4aa7ac73be214_chromedriver       0x0000000106e1b8d5 4ec4aa7ac73be214_chromedriver + 4475093
26  libsystem_pthread.dylib             0x00007fff206618fc _pthread_start + 224
27  libsystem_pthread.dylib             0x00007fff2065d443 thread_start + 15

**Running on MBP 11.6.7 (20G630)**

Python version: 3.7.12
datacamp-downloader version: 3.2
Conda version: 4.9.2

**Comment by NathanZorndorf** [comment]
Ah, it seems running `pip install datacamp-downloader` fixed the issue.
The only thing that changed was an uninstallation of the `colorama` package.
