### ISSUE TITLE
Cannot get courses

### ISSUE THREAD

**Issue by TanjimReza** [TRoboto/datacamp-downloader#59]
``datacamp courses
+--------+------------------------------------------+------------+------------+------------+
| ID     | Title                                    | Datasets   | Exercises  | Videos     |
+--------+------------------------------------------+------------+------------+------------+
Please wait —Traceback (most recent call last):
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\Scripts\datacamp.exe\__main__.py", line 7, in <module>
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\datacamp_downloader\downloader.py", line 67, in courses
    datacamp.list_completed_courses(refresh)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\datacamp_downloader\datacamp_utils.py", line 44, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\datacamp_downloader\helper.py", line 72, in wrapper
    output = f(*args)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\datacamp_downloader\datacamp_utils.py", line 181, in list_completed_courses
    for i, course in enumerate(self.get_completed_courses(refresh), 1):
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\datacamp_downloader\datacamp_utils.py", line 409, in get_completed_courses
    data = self.get_profile_data()
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\datacamp_downloader\datacamp_utils.py", line 153, in get_profile_data
    self.profile_data = self.session.get_json(
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\datacamp_downloader\session.py", line 84, in get_json
    page = self.get(url)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\datacamp_downloader\session.py", line 79, in get
    self.driver.get(url)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 535, in get
    return super().get(url)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 447, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ok\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
        Ordinal0 [0x00B46463+2188387]
        Ordinal0 [0x00ADE461+1762401]
        Ordinal0 [0x009F3D78+802168]
        Ordinal0 [0x009E7210+750096]
        Ordinal0 [0x009E675A+747354]
        Ordinal0 [0x009E5D3F+744767]
        Ordinal0 [0x009E557C+742780]
        Ordinal0 [0x009F9BF3+826355]
        Ordinal0 [0x00A4CF6D+1167213]
        Ordinal0 [0x00A3C5F6+1099254]
        Ordinal0 [0x00A16BE0+945120]
        Ordinal0 [0x00A17AD6+948950]
        GetHandleVerifier [0x00DE71F2+2712546]
        GetHandleVerifier [0x00DD886D+2652765]
        GetHandleVerifier [0x00BD002A+520730]
        GetHandleVerifier [0x00BCEE06+516086]
        Ordinal0 [0x00AE468B+1787531]
        Ordinal0 [0x00AE8E88+1805960]
        Ordinal0 [0x00AE8F75+1806197]
        Ordinal0 [0x00AF1DF1+1842673]
        BaseThreadInitThunk [0x76EE7BA9+25]
        RtlInitializeExceptionChain [0x77C5B7DB+107]
        RtlClearBits [0x77C5B75F+191]``

**Comment by bestagi** [comment]
Upgrade your Google Chrome Browser to version 105.X.XX
