### ISSUE TITLE
ModuleNotFoundError, but referred module is installed

### ISSUE THREAD

**Issue by andr3wpex** [TRoboto/datacamp-downloader#66]
datacamp --help
Traceback (most recent call last):
  File "/Users/..../.pyenv/versions/3.11.4/bin/datacamp", line 5, in <module>
    from datacamp_downloader.downloader import app
  File "/Users/..../.pyenv/versions/3.11.4/lib/python3.11/site-packages/datacamp_downloader/__init__.py", line 3, in <module>
    from .session import Session
  File "/Users/..../.pyenv/versions/3.11.4/lib/python3.11/site-packages/datacamp_downloader/session.py", line 6, in <module>
    import undetected_chromedriver.v2 as uc
ModuleNotFoundError: No module named 'undetected_chromedriver.v2'

**Comment by Istiaq-Fuad** [comment]
solved this by changing "import undetected_chromedriver.v2 as uc" to "import undetected_chromedriver as uc"
