### ISSUE TITLE
OSError: [WinError 6] The handle is invalid while running 'datacamp courses command'

### ISSUE THREAD

**Issue by NatarajMaddala** [TRoboto/datacamp-downloader#69]
When I'm running the datacamp courses command, the chrome browser pop-up opens for a second and closes. Then I'll get the below error in the cmd.

+--------+------------------------------------------+------------+------------+------------+
| ID     | Title                                    | Datasets   | Exercises  | Videos     |
+--------+------------------------------------------+------------+------------+------------+
Please wait /Exception ignored in: <function Chrome.__del__ at 0x0000022D0DB08AE0>
Traceback (most recent call last):
  File "C:\Users\mnatr\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\mnatr\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit

**Comment by Arckx** [comment]
me too

**Comment by Ben-0-mad** [comment]
I am getting the exact same error.
