### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by BaolahyJosaphat** [TRoboto/datacamp-downloader#70]
Very helpful! I'm facing the following error. How to manage?
Traceback (most recent call last):
  File "/home/baolahy/envdatacamp/bin/datacamp", line 5, in <module>
    from datacamp_downloader.downloader import app
  File "/home/baolahy/envdatacamp/lib/python3.10/site-packages/datacamp_downloader/__init__.py", line 3, in <module>
    from .session import Session
  File "/home/baolahy/envdatacamp/lib/python3.10/site-packages/datacamp_downloader/session.py", line 6, in <module>
    import undetected_chromedriver.v2 as uc
ModuleNotFoundError: No module named 'undetected_chromedriver.v2'

Thank you

**Comment by Spymik** [comment]
Try:
pip uninstall undetected_chromedriver

**Comment by alberto1989solo** [comment]
Go to session.py and change 
import undetected_chromedriver.v2 as uc
for
import undetected_chromedriver as uc

**Comment by BaolahyJosaphat** [comment]
Thank you. It works, but I cant login, even set my token. I receive 
ERROR: Binary Location Must be a String
Thank you
